/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import crud.koneksi;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author ACER
 */
public class FrameDataKota extends javax.swing.JFrame {

    private koneksi crud;
    /**
     * Creates new form FrameDataKota
     */
    public FrameDataKota() {
        
        crud = new koneksi();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid_kota = new javax.swing.JTextField();
        txtnama_kec = new javax.swing.JTextField();
        txtkota = new javax.swing.JTextField();
        txtkodepos = new javax.swing.JTextField();
        txtdeskripsi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORM DATA KOTA");

        jLabel1.setText("ID KOTA");

        jLabel2.setText("NAMA KECEMATAN");

        jLabel3.setText("KOTA");

        jLabel4.setText("KODE POS");

        jLabel5.setText("DESKRIPSI");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("DATA KOTA");

        txtnama_kec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama_kecActionPerformed(evt);
            }
        });

        txtdeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeskripsiActionPerformed(evt);
            }
        });

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CARI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnama_kec, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkodepos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdeskripsi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(txtid_kota)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel6)))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtid_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama_kec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnama_kecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama_kecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnama_kecActionPerformed

    private void txtdeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeskripsiActionPerformed
    
//    Simpan Data Kota
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if(txtid_kota.getText().equals("")){
                JOptionPane.showMessageDialog(this, "ID KOTA Belum di Isi");
                txtid_kota.requestFocus();
            } else if(txtnama_kec.getText().equals("")){
                JOptionPane.showMessageDialog(this, "NAMA KECAMATAN Belum di Isi");
                txtnama_kec.requestFocus();
            } else if(txtkota.getText().equals("")){
                JOptionPane.showMessageDialog(this, "NAMA KOTA Belum di Isi");
                txtkota.requestFocus();
            } else if(txtkodepos.getText().equals("")){
                JOptionPane.showMessageDialog(this, "KODE POS Belum di Isi");
                txtkodepos.requestFocus();
            } else if(txtdeskripsi.getText().equals("")){
                JOptionPane.showMessageDialog(this, "DESKRIPSI Belum di Isi");
                txtdeskripsi.requestFocus();
            } else {
                crud.simpandatakota(txtid_kota.getText(), txtnama_kec.getText(), txtkota.getText(), txtkodepos.getText(), txtdeskripsi.getText());
                JOptionPane.showMessageDialog(this, "Yay, DATA KOTA Berhasil Di Simpan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

//    Ubah Data Kota
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
        if (txtid_kota.getText().equals("") &&
            txtnama_kec.getText().equals("") &&
            txtkota.getText().equals("") &&
            txtkodepos.getText().equals("") &&
            txtdeskripsi.getText().equals("")) 
        {
                
            JOptionPane.showMessageDialog(this, "Silahkan Cari Data Kota Terlebih Dahulu");
            txtid_kota.requestFocus();
        } else {
            crud.ubahdatakota(txtid_kota.getText(), txtnama_kec.getText(), txtkota.getText(), txtkodepos.getText(), txtdeskripsi.getText());
            JOptionPane.showMessageDialog(this, "Yay, DATA KOTA Berhasil Di Ubah");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

//    hapus Data Kota
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                 txtid_kota.getText().equals("") &&
                 txtnama_kec.getText().equals("") &&
                 txtkota.getText().equals("") &&
                 txtkodepos.getText().equals("") &&
                 txtdeskripsi.getText().equals("")
                )
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                txtid_kota.requestFocus();
            } else {
                crud.hapusdatakota(txtid_kota.getText());
                JOptionPane.showMessageDialog(this, "Yay, DATA KOTA Berhasil berhasil dihapus");
                txtid_kota.getText();
                txtnama_kec.getText();
                txtkota.getText();
                txtkodepos.getText();
                txtdeskripsi.getText();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed
//  cari Data KOta
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String idKota = txtid_kota.getText();
        try {
            // Cek apakah ID Kota tidak kosong
            if (!idKota.equals("")) {
                // Panggil metode caridatakota dari objek koneksi
                ResultSet rs = crud.caridatakota(idKota);
                // Periksa apakah hasil pencarian tidak kosong
                if (rs.next()) {
                    // Jika ada hasil, tampilkan informasi dari hasil pencarian
                    String namaKec = rs.getString("nama_kec");
                    String namaKota = rs.getString("kota");
                    String kodePos = rs.getString("kodepos");
                    String deskripsi = rs.getString("deskripsi");
                    // Tampilkan informasi pada antarmuka pengguna
                    txtnama_kec.setText(namaKec);
                    txtkota.setText(namaKota);
                    txtkodepos.setText(kodePos);
                    txtdeskripsi.setText(deskripsi);
                    JOptionPane.showMessageDialog(this, "Yay, Data Kota ditemukan");
                } else {
                    // Jika tidak ada hasil, tampilkan pesan bahwa data tidak ditemukan
                    JOptionPane.showMessageDialog(this, "Yah, Data Kota tidak ditemukan");
                }
            } else {
                // Jika ID Kota kosong, minta pengguna untuk mengisi ID Kota terlebih dahulu
                JOptionPane.showMessageDialog(this, "Masukkan ID Kota terlebih dahulu");
            }
        } catch (Exception e) {
            // Tangani jika terjadi kesalahan saat mencari data
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDataKota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDataKota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDataKota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDataKota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDataKota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtdeskripsi;
    private javax.swing.JTextField txtid_kota;
    private javax.swing.JTextField txtkodepos;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtnama_kec;
    // End of variables declaration//GEN-END:variables
}
