/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import crud.koneksi;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author ACER
 */
public class FrameBerita extends javax.swing.JFrame {

    private koneksi crud;
    /**
     * Creates new form FrameBerita
     */
    public FrameBerita() {
        crud = new koneksi();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid_berita = new javax.swing.JTextField();
        txttanggal_post = new javax.swing.JTextField();
        txtgambar = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtkonten = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORM BERITA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BERITA");

        jLabel2.setText("ID BERITA");

        jLabel3.setText("TANGGAL POST");

        jLabel4.setText("GAMBAR");

        jLabel5.setText("JUDUL");

        jLabel6.setText("KONTEN");

        txtgambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgambarActionPerformed(evt);
            }
        });

        jButton1.setText("SIMPAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("UBAH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("CARI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgambar)
                    .addComponent(txtjudul)
                    .addComponent(txtkonten)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(txtid_berita)
                    .addComponent(txttanggal_post))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid_berita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttanggal_post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkonten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgambarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgambarActionPerformed
// simpan Berita
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            if(txtid_berita.getText().equals("")){
                JOptionPane.showMessageDialog(this, "ID BERITA Belum di Isi");
                txtid_berita.requestFocus();
            } else if(txttanggal_post.getText().equals("")){
                JOptionPane.showMessageDialog(this, "TANGGAL POST Belum di Isi");
                txttanggal_post.requestFocus();
            } else if(txtgambar.getText().equals("")){
                JOptionPane.showMessageDialog(this, "GAMBAR Belum di Isi");
                txtgambar.requestFocus();
            }  else if(txtjudul.getText().equals("")){
                JOptionPane.showMessageDialog(this, "JUDUL Belum di Isi");
                txtjudul.requestFocus(); 
            } else if(txtkonten.getText().equals("")){
                JOptionPane.showMessageDialog(this, "KONTEN Belum di Isi");
                txtkonten.requestFocus();
            } else {
                crud.simpanberita(txtid_berita.getText(), txttanggal_post.getText(), txtgambar.getText(), txtjudul.getText(), txtkonten.getText());
                JOptionPane.showMessageDialog(this, "Yay, BERITA Berhasil Di Simpan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }                                        
    }//GEN-LAST:event_jButton1ActionPerformed
//  ubah Berita
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
            if (txtid_berita.getText().equals("") &&
                txttanggal_post.getText().equals("") &&
                txtgambar.getText().equals("") &&
                txtjudul.getText().equals("") &&
                txtkonten.getText().equals("")) 
            {    
                JOptionPane.showMessageDialog(this, "Silahkan Cari Data Komentar Terlebih Dahulu");
                txtid_berita.requestFocus();
            } else {
                crud.ubahberita(txtid_berita.getText(), txttanggal_post.getText(), txtgambar.getText(), txtjudul.getText(), txtkonten.getText());
                JOptionPane.showMessageDialog(this, "Yay, BERITA Berhasil Di Ubah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } 
    }//GEN-LAST:event_jButton2ActionPerformed
// hapus Berita
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            if (
                 txtid_berita.getText().equals("") &&
                 txttanggal_post.getText().equals("") &&
                 txtgambar.getText().equals("") &&
                 txtjudul.getText().equals("") &&
                 txtkonten.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Silahkan cari data terlebih dahulu");
                txtid_berita.requestFocus();
            } else {
                crud.hapusberita(txtid_berita.getText());
                JOptionPane.showMessageDialog(this, "Yay, BERITA Berhasil berhasil dihapus");
                txtid_berita.getText();
                txttanggal_post.getText();
                txtgambar.getText();
                txtjudul.getText();
                txtkonten.getText();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String idBerita = txtid_berita.getText();
        try {
            // Cek apakah ID Berita tidak kosong
            if (!idBerita.equals("")) {
                // Panggil metode cariBerita dari objek koneksi
                ResultSet rs = crud.cariberita(idBerita);
                // Periksa apakah hasil pencarian tidak kosong
                if (rs.next()) {
                    // Jika ada hasil, tampilkan informasi dari hasil pencarian
                    String tanggalpost = rs.getString("tanggal_post");
                    String gambar = rs.getString("gambar");
                    String judul = rs.getString("judul");
                    String konten = rs.getString("konten");
                    // Tampilkan informasi pada antarmuka pengguna
                    txttanggal_post.setText(tanggalpost);
                    txtgambar.setText(gambar);
                    txtjudul.setText(judul);
                    txtkonten.setText(konten);
                    JOptionPane.showMessageDialog(this, "Yay, Data Berita ditemukan");
                } else {
                    // Jika tidak ada hasil, tampilkan pesan bahwa data tidak ditemukan
                    JOptionPane.showMessageDialog(this, "Yah, Data Berita tidak ditemukan");
                }
            } else {
                // Jika ID Berita kosong, minta pengguna untuk mengisi ID Wisata terlebih dahulu
                JOptionPane.showMessageDialog(this, "Masukkan ID Berita terlebih dahulu");
            }
        } catch (Exception e) {
            // Tangani jika terjadi kesalahan saat mencari data
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBerita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBerita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBerita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBerita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBerita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtgambar;
    private javax.swing.JTextField txtid_berita;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtkonten;
    private javax.swing.JTextField txttanggal_post;
    // End of variables declaration//GEN-END:variables
}
